// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx7WD7EI-hAU0d-7FsM_JvlfoQ1braDIg',
    appId: '1:39469612156:web:a9dcd9b46e5ec8835b5df9',
    messagingSenderId: '39469612156',
    projectId: 'wardrobewizardapp-c0705',
    authDomain: 'wardrobewizardapp-c0705.firebaseapp.com',
    storageBucket: 'wardrobewizardapp-c0705.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ja2e8Yki6e5KzVq4vOE-E2lAvqgHitA',
    appId: '1:39469612156:android:aca185d459147d4f5b5df9',
    messagingSenderId: '39469612156',
    projectId: 'wardrobewizardapp-c0705',
    storageBucket: 'wardrobewizardapp-c0705.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx7WD7EI-hAU0d-7FsM_JvlfoQ1braDIg',
    appId: '1:39469612156:web:e51a10039fd2e1085b5df9',
    messagingSenderId: '39469612156',
    projectId: 'wardrobewizardapp-c0705',
    authDomain: 'wardrobewizardapp-c0705.firebaseapp.com',
    storageBucket: 'wardrobewizardapp-c0705.appspot.com',
  );
}
